# Generated by Django 5.1 on 2024-09-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_clone', '0002_auto_20240903_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='retweets',
        ),
    ]
